version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - echo nothing to build yet

artifacts:
  files:
    - index.html
    - favicon.ico
    - justin-sparks-resume-9-23-2019.pdf
    - styles/main.css
    - images/*
    