version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install 
      - npm run webpack

artifacts:
  files:
    - index.html
    - justin-sparks-resume-9-23-2019.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
    